#!/bin/bash

# Script to fix problematic relative imports
# Generated by find_problematic_imports.sh

echo "Fixing problematic imports..."

echo "Fixing ./config/__init__.py..."
sed -i 's/from \.\./from /g' "./config/__init__.py"

echo "Fixing ./config/settings.py..."
sed -i 's/from \.\./from /g' "./config/settings.py"

echo "Fixing ./models/cell_extractor.py..."
sed -i 's/from \.\./from /g' "./models/cell_extractor.py"

echo "Fixing ./models/digit_recognizer.py..."
sed -i 's/from \.\./from /g' "./models/digit_recognizer.py"

echo "Fixing ./models/grid_reconstructor.py..."
sed -i 's/from \.\./from /g' "./models/grid_reconstructor.py"

echo "Fixing ./models/__init__.py..."
sed -i 's/from \.\./from /g' "./models/__init__.py"

echo "Fixing ./models/intersection_detector.py..."
sed -i 's/from \.\./from /g' "./models/intersection_detector.py"

echo "Fixing ./models/solver.py..."
sed -i 's/from \.\./from /g' "./models/solver.py"

echo "Fixing ./utils/data_preparation.py..."
sed -i 's/from \.\./from /g' "./utils/data_preparation.py"

echo "Fixing ./utils/handling.py..."
sed -i 's/from \.\./from /g' "./utils/handling.py"

echo "Fixing ./utils/metrics.py..."
sed -i 's/from \.\./from /g' "./utils/metrics.py"

echo "Fixing ./utils/visualization.py..."
sed -i 's/from \.\./from /g' "./utils/visualization.py"

echo "All imports fixed!"
echo "Please test your code to ensure everything works correctly."

# Fix special case in train.py
echo "Fixing special case in train.py..."
sed -i 's/from config import initialize_settings/from config.settings import initialize_settings/g' "train.py"
